# Generated by Django 3.1.4 on 2022-06-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220619_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
